### ISSUE TITLE
numbers are not treated as JSX variables

### ISSUE THREAD

**Issue by aleedmanath** [squint-cljs/compiler-common#7]
error: 
```
JSX value should be either an expression or a quoted JSX text
   ,----
 3 | { let x55 = <Flex marginTop=100 >{ (function () {
   :                             ^^^
```

should be `marginTop={100}`

**Comment by borkdude** [comment]
@aleedmanath Thanks. I vaguely remember fixing this once already... :) Would you like to try a PR or do you want for someone else to do it?

**Comment by borkdude** [comment]
Ah yes, here it is mentioned...:

https://github.com/squint-cljs/compiler-common/blob/main/cherry/CHANGELOG.md#000-alpha57

**Comment by aleedmanath** [comment]
hm, i'm on `0.0.0-alpha.60` 

i'm testing build tool integration, so i'll definitely fork and see what's up

but i'm going to also be integrating my own hiccup compiler so may be a little before I swing back

**Comment by borkdude** [comment]
The JSX tests are here:

https://github.com/squint-cljs/compiler-common/blob/main/cherry/test/cherry/jsx_test.cljs

If you can provide a PR as failing test, that would be a good start.

**Comment by aleedmanath** [comment]
thanks for the link, I was looking at compiler-common since some jsx logic was there

**Comment by borkdude** [comment]
yes, but compiler-common is tested in both squint and cherry.

**Comment by aleedmanath** [comment]
you're right, a basic test for this works

there's other tools processing the JSX so may be getting mishandled somewhere

but i'll re-open if anything; thanks

**Comment by aleedmanath** [comment]
oh just considered, maybe transpiling to commonjs is messing with the output

posting for posterity. will test that out and see if I can get build to work with es6
